# Configuración del sitio
title: Portafolio de Prácticas - joizquie
email: joizquie@unirioja.es
description: >- # this means to ignore newlines until "baseurl:"
  Este es mi espacio personal para la documentación de las prácticas
  de la asignatura. Aquí se detalla mi trabajo con GitHub y Jekyll.
baseurl: "/mi-cv-jekyll" # the subpath of your site, e.g. /blog
url: "https://joizquie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joizquie
github_username:  joizquie

# Build settings
theme: minima
plugins:
  - jekyll-feed
  
